### ISSUE TITLE
Add device attributes and location details as labels to BD resources

### ISSUE THREAD

**Issue by kmova** [openebs/node-disk-manager#615]
**Describe the problem/challenge you have**

There is no easy way to filter the block device resources based on generic attributes like - drive type, model/vendor. This limits the flexibility in terms of how a block device can be used by high-level abstractions like Device Local PV - which should specify the type of block devices to be used for a given storage class. [ Ref: https://github.com/openebs/dynamic-localpv-provisioner/issues/35 ]. 

The current workaround to group the devices together is to use a "block device tag" that has to be manually configured on each of the block devices, once the block device is created. Or enhance the logic of discovery probes to create block device tag based on configuration. 

**Describe the solution you'd like**

NDM should automatically update the metadata of the Block Device Resources with generic labels that it currently adds to the spec. Like:
```
apiVersion: v1
items:
- apiVersion: openebs.io/v1alpha1
  kind: BlockDevice
  metadata:
    labels:
      kubernetes.io/hostname: gke-kmova-helm-default-pool-30f2c6c6-qf2w
      ndm.io/blockdevice-type: blockdevice
      ndm.io/managed: "true"
      ndm.io/vendor: "Google"
      ndm.io/model: "EphemeralDisk"
      ndm.io/drive-type: "SSD"
      ndm.io/filesystem-type: "ext4"
  spec:
    capacity:
      logicalSectorSize: 4096
      physicalSectorSize: 4096
      storage: 402653184000
    details:
      compliance: SPC-4
      deviceType: disk
      driveType: SSD
      firmwareRevision: '1   '
      hardwareSectorSize: 4096
      logicalBlockSize: 4096
      model: EphemeralDisk
      physicalBlockSize: 4096
      serial: local-ssd-2
      vendor: Google
    devlinks:
    - kind: by-id
      links:
      - /dev/disk/by-id/scsi-0Google_EphemeralDisk_local-ssd-2
      - /dev/disk/by-id/google-local-ssd-2
    - kind: by-path
      links:
      - /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:3:0
    filesystem:
      fsType: ext4
      mountPoint: /mnt/disks/ssd2
```

**Anything else you would like to add:**
In addition to the standard `kubernetes.io/hostname` label, it will be nice if the NDM can also discover and attach other topology labels. For example the following labels can be really useful while claiming devices. 

```
kubernetes.io/hostname=gke-kmova-helm-default-pool-30f2c6c6-qf2w,
kubernetes.io/arch=amd64,
beta.kubernetes.io/instance-type=n1-standard-2,
failure-domain.beta.kubernetes.io/region=us-central1,
failure-domain.beta.kubernetes.io/zone=us-central1-a,
node.kubernetes.io/instance-type=n1-standard-2,
topology.kubernetes.io/region=us-central1,
topology.kubernetes.io/zone=us-central1-a
```

The list of labels to be discovered and added to the block device resource can be configured via an ENV variable to the NDM DaemonSet. 

**Environment:**
- OpenEBS version: 2.12 and earlier
